### ISSUE TITLE
Make a dictionary on another languange

### ISSUE THREAD

**Issue by dizzyname** [mammothb/symspellpy#10]
Hai Mammothb, How i can make dictionary file like yours in another languange ?
Or maybe you can explain to me How do you make frequency_dictionary_en_82_765.txt ? Please.

By the way Good project

**Comment by mammothb** [comment]
Hi, I did not make the frequency dictionary. The [original creator](https://github.com/wolfgarbe/SymSpell) did. He has included a [short description](https://github.com/wolfgarbe/SymSpell#frequency-dictionary) on how he created the dictionary. Perhaps you could direct the question to him?

**Comment by dizzyname** [comment]
Thanks mammothb for your answer, i'll ask to him

**Comment by mzeidhassan** [comment]
Hi @mammothb , sorry to reopen this, but I think this could be useful. Is there any chance you add this to your current port of Symspell?

The author tried to provide Python code to create the frequency dictionary. 

https://medium.com/@wolfgarbe/what-do-i-need-to-build-my-own-freq-dictionary-using-symspell-createdictionary-8c5c4882552

**Comment by mammothb** [comment]
Implemented in [v6.3.6](https://github.com/mammothb/symspellpy/tree/v6.3.6)
