### ISSUE TITLE
ignore_term_with_digits doesn't work

### ISSUE THREAD

**Issue by xcTorres** [mammothb/symspellpy#100]
MAX_EDIT_DISTANCE = 2

address_str = '005'
suggestions = city_state_spelling_corrector.lookup_compound(address_str,
                                                            max_edit_distance=MAX_EDIT_DISTANCE,
                                                            ignore_term_with_digits=True,
                                                            transfer_casing=False)
for suggestion in suggestions:
    print(str(suggestion))

Here is the output  
i di

**Comment by mammothb** [comment]
Sorry about that, `ignore_term_with_digits=True` only works when `ignore_non_words=True` as well, I should have make that cleared in the documentation and print a warning if only `ignore_term_with_digits=True` is used.

I tried your sample input by adapting an example from the documentation and I think it managed to give the output you were originally expecting.
```python
import pkg_resources

from symspellpy import SymSpell

sym_spell = SymSpell(max_dictionary_edit_distance=2, prefix_length=7)
dictionary_path = pkg_resources.resource_filename(
    "symspellpy", "frequency_dictionary_en_82_765.txt"
)
bigram_path = pkg_resources.resource_filename(
    "symspellpy", "frequency_bigramdictionary_en_243_342.txt"
)
# term_index is the column of the term and count_index is the
# column of the term frequency
sym_spell.load_dictionary(dictionary_path, term_index=0, count_index=1)
sym_spell.load_bigram_dictionary(bigram_path, term_index=0, count_index=2)


input_term = "005"
# max edit distance per lookup (per single word, not per whole input string)
suggestions = sym_spell.lookup_compound(
    input_term, max_edit_distance=2, ignore_non_words=True, ignore_term_with_digits=True
)
# display suggestion term, edit distance, and term frequency
for suggestion in suggestions:
    print(suggestion)
```
Output: `005, 0, 0`

**Comment by xcTorres** [comment]
Thanks for the explanation.
