### ISSUE TITLE
Need Python 2.x build

### ISSUE THREAD

**Issue by manishbansal-fk** [mammothb/symspellpy#11]
Hi,
We are not able to find package on pypi for python2.x

- Tried installing using "python setup.py install" but it throws error for python2.7 
```
    "Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    encoding="utf-8") as infile:
TypeError: 'encoding' is an invalid keyword argument for this function"
```

Is there any means we can build for python 2.x, please assist.

**Comment by mammothb** [comment]
Hi, 
So far, I have only been doing python3.x builds, I'll look into python2.x build when I have more time.

For that error, I can think of two possible fixes
1. Change [line 150](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L150) of `symspell.py` to
```python
with open(corpus, "r") as infile:
```
Note that you will not be able to specify the encoding of the dictionary file if you do this.

2. Add `import codecs` at [the top](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L1) of `symspell.py` and change [line 150](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L150) to
```python
with codecs.open(corpus, "r", encoding=encoding) as infile:
```
When I briefly tried this on my system (Ubuntu 16.04, python 2.7.12 64-bit), it didn't work with non-english dictionaries.

I hope that helps.

**Comment by manishbansal-fk** [comment]
Thanks @mammothb :)

This helped us a lot. After changing to "codecs.open()" in symspellpy and adding "**# coding=utf-8**" in the beginning of files helpers & test file, its working with python 2.7.

Is this enough ? please confirm

**Comment by mammothb** [comment]
Yes, I believe that these changes are sufficient

**Comment by manishbansal-fk** [comment]
Thanks once again 👍
