### ISSUE TITLE
wrong word segmentation result

### ISSUE THREAD

**Issue by pineking** [mammothb/symspellpy#116]
input_term="ilove my family"
suggestions = sym_spell.word_segmentation(input_term)

The result is still "ilove my family", the correct result should be "i love my family"

**Comment by mammothb** [comment]
Hi @pineking I have tried input term you used with the following code
```python
import pkg_resources

from symspellpy.symspellpy import SymSpell

sym_spell = SymSpell(max_dictionary_edit_distance=0, prefix_length=7)
dictionary_path = pkg_resources.resource_filename(
    "symspellpy", "frequency_dictionary_en_82_765.txt"
)
sym_spell.load_dictionary(dictionary_path, term_index=0, count_index=1)

input_term = "ilove my family"
result = sym_spell.word_segmentation(input_term)
print(f"{result.corrected_string}, {result.distance_sum}, {result.log_prob_sum}")
```
and I was able to get the expected correct result of
```
i love my family, 1, -12.819643708790021
```

Can you try that code snippet and see if you can get the same result as I have?
