### ISSUE TITLE
pip install cannot find symspellpy

### ISSUE THREAD

**Issue by xulifan** [mammothb/symspellpy#12]
>pip install -U symspellpy
Collecting symspellpy
  Could not find a version that satisfies the requirement symspellpy (from versions: )
No matching distribution found for symspellpy

**Comment by mammothb** [comment]
What version of Python are you using?

**Comment by xulifan** [comment]
Python 2.7.12

**Comment by mammothb** [comment]
Currently, only Python 3.x builds are available, you could follow some of the modifications in [this issue](https://github.com/mammothb/symspellpy/issues/11) and do a manual build using `python setup.py install`

**Comment by xulifan** [comment]
Thanks!
