### ISSUE TITLE
error if i use spell checker to my dataset

### ISSUE THREAD

**Issue by nickokiller2** [mammothb/symspellpy#123]
i already can use your library but if im applied to my dataset i got error, maybe you can help me

`#this code is work and i already defined sym_spell as dictionary from wiki
from symspellpy import SymSpell, Verbosity

input_term = "diberbaikin tertnduk kenaps"
suggestions = sym_spell.lookup_compound(input_term, max_edit_distance=2)

for suggestion in suggestions:
    print(suggestion.term)
#output : diperbaiki tertunduk kenapa

#this the code and error
comment = []
for index, row in df.iterrows():
    suggestions = sym_spell.lookup_compound(row["Comment"], max_edit_distance=2)
    comment.append(suggestions[0].term)
    
df["Comment"] = comment
df.head()

#error
AttributeError                            Traceback (most recent call last)
[<ipython-input-70-8758d0e7f72e>](https://localhost:8080/#) in <module>()
      1 comment = []
      2 for index, column in df.iterrows():
----> 3     suggestions = sym_spell.lookup_compound(column["Comment"], max_edit_distance=2)
      4     comment.append(suggestions[0].term)
      5 

1 frames
[/usr/local/lib/python3.7/dist-packages/symspellpy/helpers.py](https://localhost:8080/#) in parse_words(phrase, preserve_case, split_by_space)
    196     if preserve_case:
    197         return re.findall(r"([^\W_]+['’]*[^\W_]*)", phrase)
--> 198     return re.findall(r"([^\W_]+['’]*[^\W_]*)", phrase.lower())
    199 
    200 

AttributeError: 'float' object has no attribute 'lower'`

**Comment by mammothb** [comment]
> AttributeError: 'float' object has no attribute 'lower'`

From the error message, it suggests that the `Comment` column contains float values instead of all strings.

**Comment by nickokiller2** [comment]
sorry im newbie what is that mean? what do you mean there is an empty row or it only contains symbols?

**Comment by mammothb** [comment]
There's a row that contain only numbers.

**Comment by nickokiller2** [comment]
oke sir thank you for helping me 👌
