### ISSUE TITLE
Missing Word Segmentation from SymSpell

### ISSUE THREAD

**Issue by manishbansal-fk** [mammothb/symspellpy#13]
Missing Word Segmentation from https://github.com/wolfgarbe/SymSpell. Please suggest.

**Comment by mammothb** [comment]
I did not implement yet since I didn't need the feature when I started porting SymSpell. I will look into it when I have time

**Comment by mammothb** [comment]
@manishbansal-fk i have published a new release which includes the `word_segmentation` feature, please try it out and let me know if you encounter any bugs

**Comment by manishbansal-fk** [comment]
@mammothb We will check this out. Thanks a lot for your time 👍
