### ISSUE TITLE
Custom Edit Distance

### ISSUE THREAD

**Issue by e-barrere** [mammothb/symspellpy#130]
Hello,

I would like to adapt the edit distance weights used to minimize the cost of replacing unaccented letters with accented ones (this method is more suitable for French). Is there a way to use a custom distance in Symspell ?  

Thank you

**Comment by mammothb** [comment]
Currently there is not official way to use custom edit distance weights.

With reference to https://medium.com/@chipiga86/python-monkey-patching-like-a-boss-87d7ddb8098e, I was able to patch in a custom edit distance comparer:

Directory structure
```
project_dir
+-monkeypatch.py
+-main.py
\-...
```

Note the order or imports, use of `monkey.uncache()`, and setting `sym_spell.distance_algorithm = monkeypatch.DistanceAlgorithm.CUSTOM`.

```python
# main.py

import pkg_resources

import monkeypatch
import symspellpy.editdistance

symspellpy.editdistance.DistanceAlgorithm = monkeypatch.DistanceAlgorithm
symspellpy.editdistance.EditDistance = monkeypatch.EditDistance
monkeypatch.uncache(["symspellpy.editdistance"])
from symspellpy import SymSpell, Verbosity

sym_spell = SymSpell(max_dictionary_edit_distance=2, prefix_length=7)
sym_spell.distance_algorithm = monkeypatch.DistanceAlgorithm.CUSTOM
dictionary_path = pkg_resources.resource_filename(
    "symspellpy", "frequency_dictionary_en_82_765.txt"
)
# term_index is the column of the term and count_index is the
# column of the term frequency
sym_spell.load_dictionary(dictionary_path, term_index=0, count_index=1)

# lookup suggestions for single-word input strings
input_term = "memebers"  # misspelling of "members"
# max edit distance per lookup
# (max_edit_distance_lookup <= max_dictionary_edit_distance)
suggestions = sym_spell.lookup(input_term, Verbosity.CLOSEST, max_edit_distance=2)
# display suggestion term, edit distance, and term frequency
for suggestion in suggestions:
    print(suggestion)
```
You should get 
```
members, 1, 226656153
```
I've included the files (main.py and monkeypatch.py) 
[sandbox.zip](https://github.com/mammothb/symspellpy/files/9786793/sandbox.zip)

If I understood your question correctly, the `CustomComparer` in `monkeypatch.py` should be the class you're looking to modify to implement custom edit distance weights.

**Comment by e-barrere** [comment]
Yes this is what I wanted to do. Thank you for your answer !

**Comment by mammothb** [comment]
This is now officially supported through https://github.com/mammothb/symspellpy/pull/159
