### ISSUE TITLE
how do i add new terms?

### ISSUE THREAD

**Issue by fahadshery** [mammothb/symspellpy#14]
Hi,

Apologies for using the issue tracker to ask a question.

How do I add a replacement for `gr8` to `great`?? Is there a way to augment/extend the existing dictionary `frequency_dictionary_en_82_765.txt` to include these replacements? if yes how?

Best wishes and great work!

**Comment by mammothb** [comment]
you can follow one of the two methods listed here https://github.com/mammothb/symspellpy/issues/9#issuecomment-431215690
