### ISSUE TITLE
Get the number of misspelled words

### ISSUE THREAD

**Issue by MertonL** [mammothb/symspellpy#16]
It would be useful if `lookup_compound` could return the number of words it has fixed, or perhaps a different method which only checks for the number of mistakes and returns the total.

Is this possible with the current implementation?

**Comment by hnikana** [comment]
Is there any method to check the accuracy ? I believe it is something should be done manually or by sampling over the corrected words. But there should be a method to give the list of corrected word and their replacements? Would you please let me know whether it exists ?

**Comment by mammothb** [comment]
Checking for accuracy is all done in the `lookup` method, there isn't a separate method for that. Maybe it would be better to check with the [original developer](https://github.com/wolfgarbe/SymSpell) as he should be more knowledgeable on the underlying algorithm

**Comment by hnikana** [comment]
IN the look up method I found out the number of words which is corrected but I need the list of them and their replacement. 
One more question , do you know any dictionary for Electronic Health Note containing medical terminology or trained for this purpose?

**Comment by mammothb** [comment]
No, I don't know of any. Sorry

**Comment by mammothb** [comment]
Number of misspelled words can now be determined through `<self._replaced_words = dict()>` introduced in #18
