### ISSUE TITLE
lookup('correcn', 1) doesn't output anything. 

### ISSUE THREAD

**Issue by why-not** [mammothb/symspellpy#2]
I see the word "correct" in the supplied dictionary, and yet when I tried to load it and do the above lookup it doesn't output anything. Am I doing something wrong, are you seeing any output?

**Comment by jeicoo** [comment]
You need to run `load_dictionary` before doing any lookup.

```
sym_spell = SymSpell()
sym_spell.load_dictionary('corpus.txt', 0, 1)

result = sym_spell.lookup('samlpe', 1)
```

**Comment by jeicoo** [comment]
You can even check if the dictionary loaded correctly,
```
len(sym_spell.words)
```

**Comment by why-not** [comment]
Yes, I did load the dictionary and tried a few other inputs which worked. If it works on your end, Let me go ahead and close it. I will try this out again when I am on a terminal again and report back.
