### ISSUE TITLE
How to create another dictionary 

### ISSUE THREAD

**Issue by hnikana** [mammothb/symspellpy#20]
hello, 

I wanted to modify the existing dictionary by adding some words to it for the purpose of EHR (electronic health record ) analysis. Unfortunately , the program does not read my file properly. I used the pandas package to read the existing dictionary , the new one I want to add to and drop the  duplicate. But it does not work . Any clue how to solve the issue ? 

```python
dic_1 = pd.read_csv('frequency_dictionary_en_82_765.txt' , delimiter=" " , header=None)
dic_2 = pd.read_csv('medical_wordlist_original.txt',delimiter=" ", header=None,error_bad_lines=False)
dic_2[0]= dic_2[0].str.lower()
dic_big = pd.concat([dic_1,dic_2],ignore_index=True)

dic_big.fillna(floor(dic_big.mean()), inplace=True)
dic_big.sort_values(by = [1] ,ascending=0 , inplace=True)
dic_big.drop_duplicates(subset=0,keep='first', inplace = True)

dic_big.to_csv('dictionary.txt' , sep=" ", index=False, header=False , encoding ='utf-8' )

```
Another way I tried was to just add the new terminologies to the existing dictionary but that way , I could not take care of duplicated terms. 

Another question is that , Should the new dictionary be sorted down by frequency or it does not matter ? How about the duplicated terms ? what if there is not frequency in our dictionary , would it work ? why ?

**Comment by mammothb** [comment]
What do you mean by it does not work? I tried it on my side and I think I managed to get a new dictionary `dictionary.txt` with all the words combined and duplicated terms dropped.

Assume the following directory structure:
```
dir
+---dictionary.txt (to be generated)
+---frequency_dictionary_en_82_765.txt
+---medical_wordlist_original.txt
\---combidict.py
```
Contents of `frequency_dictionary_en_82_765.txt`
```
the 23135851162
of 13151942776
and 12997637966
to 12136980858
a 9081174698
```
Contents of `medical_wordlist_original.txt`
```
the 23135851162
qqqof 13151942776
and 12997637966
qqqto 12136980858
a 9081174698
```
Word with the `qqq` prefix are new words, the rest are duplicates. So we should end up with a new dictionary of 7 words.

Contents of `combidict.py`
```python
import math

import pandas as pd

dic_1 = pd.read_csv("frequency_dictionary_en_82_765.txt", delimiter=" ",
                    header=None)
dic_2 = pd.read_csv("medical_wordlist_original.txt", delimiter=" ",
                    header=None, error_bad_lines=False)
dic_2[0]= dic_2[0].str.lower()
dic_big = pd.concat([dic_1, dic_2], ignore_index=True)

dic_big.fillna(math.floor(dic_big.mean()), inplace=True)
dic_big.sort_values(by=[1], ascending=0, inplace=True)
dic_big.drop_duplicates(subset=0, keep="first", inplace=True)

dic_big.to_csv("dictionary.txt", sep=" ", index=False, header=False,
               encoding="utf-8")
```
Contents of `dictionary.txt`
```
the 23135851162
of 13151942776
qqqof 13151942776
and 12997637966
to 12136980858
qqqto 12136980858
a 9081174698
```

You don't need to sort the dictionary by frequency.

For duplicated terms, the frequency will be summed so you are probably right in wanting to remove duplicates beforehand.

We require the dictionary file to have at least 2 columns, if not, that line (word) will be skipped. https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L158

**Comment by hnikana** [comment]
Thanks for replying and verification. However, I meant that the load.dictionary () was not able to read the dictionary.txt . 
I found out the problem and just wanted to share with you as well. 

In to_csv() function the frequencies (count) are read in float format and the   helpers.try_parse_int64(string) [https://github.com/mammothb/symspellpy/blob/dd168a385b945ba835a02a19d0aad6acfb1c7f24/symspellpy/helpers.py#L41](url) will skip it if it is not in the integer format, however, pandas.to_csv() reads the in float format if you do not introduce the "float_format" argument in it properly. so with the modified line below , it works fine and dictionary.txt would be fully compatible with the required format. 

`dic_big.to_csv('dictionary.txt' , sep=" ", index=False, header=False , encoding ='utf-8' , float_format='%d' )`

if you feel that would be the help to the package I can add it as a function in helpers. 

thanks

**Comment by mammothb** [comment]
Thank you for offering but I don't think it's necessary. This issue should be sufficient for others who encounter similar problems in the future.

**Comment by hnikana** [comment]
great

**Comment by MukhtarShaima** [comment]
Hie,
I'm working with Urdu language,and my dict has unique values,so for the freq count I added 1 for each term.
Now, when i tried with single_word input string, it returns same value.
یہیضن, 0, 0

Can anyone please help me,whats the problem here.
[temp.py.txt](https://github.com/mammothb/symspellpy/files/2899496/temp.py.txt)
[Book2.txt](https://github.com/mammothb/symspellpy/files/2899498/Book2.txt)

**Comment by hnikana** [comment]
`import pandas as pd 
from math import floor 
import numpy as np

dic_1 = pd.read_csv('frequency_dictionary_en_82_765.txt' , delimiter=" " , header=None)
dic_2 = pd.read_csv('medical_wordlist_original.txt',delimiter=" ", header=None,error_bad_lines=False)
dic_2[0]= dic_2[0].str.lower()
dic_big = pd.concat([dic_1,dic_2],ignore_index=True)
dic_big.fillna(20000000000, inplace=True)
dic_big.sort_values(by = [1] ,ascending=0 , inplace=True)
dic_big.drop_duplicates(subset=0,keep='first', inplace = True)

dic_big.to_csv('dictionary.txt' , sep=" ", index=False, header=False , encoding ='utf-8' , float_format='%d' )

`
This is the way I combined two dictionary but in your case you have to follow the strict format of creating your own dictionary . 

Dictionary could have not frequency but I would suggest put the same number for all of them if you do not have any word frequency.
