### ISSUE TITLE
pip install -U not updating with the new methods

### ISSUE THREAD

**Issue by fahadshery** [mammothb/symspellpy#26]
Hi,

Saw you implemented the create_dictionary(). But I can't update the package even after running the `pip install`. Could you help? 
Sorry I am an R user so learning python at the same time.
Ta

**Comment by mammothb** [comment]
When you run `pip install -U symspellpy`, what output do you see?

And when you do `pip freeze | grep symspellpy`, what do you see? Use `pip freeze | Select-String -Pattern "symspellpy"` if you're on Windows.

**Comment by fahadshery** [comment]
> When you run `pip install -U symspellpy`, what output do you see?
`$ pip install -U symspellpy`
`Collecting symspellpy`
`  Downloading` `https://files.pythonhosted.org/packages/43/af/d7bec0d65aa916d47b92fa6ac5eafc9a833a3d2f8d7adabcef3ba47a52d6/symspellpy-6.3.6-py3-none-any.whl`
`Requirement already satisfied, skipping upgrade: numpy>=1.13.1 in c:\users\607518069\appdata\local\continuum\anaconda3\lib\site-packages (from symspellpy) (1.15.4)`
`Installing collected packages: symspellpy`
`  Found existing installation: symspellpy 6.3.5`
`    Uninstalling symspellpy-6.3.5:`
`      Successfully uninstalled symspellpy-6.3.5`
`Successfully installed symspellpy-6.3.6`

> And when you do `pip freeze | grep symspellpy`, what do you see?
`$ pip freeze | grep symspellpy`
`symspellpy==6.3.6`

**Comment by mammothb** [comment]
It shows that you have successfully installed symspellpy, are you still not able to use `create_dictionary`?

**Comment by fahadshery** [comment]
Yes I can. Had to restart Anaconda :) sorry. please close this.

The final question I have is, some times you have a text file with misspellings. I think ideally, we should be able to correct those misspellings prior to creating a dictionary from the text file.

**Comment by mammothb** [comment]
I am thinking that we could just run symspellpy with the provided ` 	frequency_dictionary_en_82_765.txt` before creating a dictionary from the text file. This could be done by the users in their project files so I don't think we need to include a function/method for this in the package. But if you had any other suggestions on how we can do this, open a new issue and we can discuss there.

**Comment by fahadshery** [comment]
No this makes sense. do the spell check/corrections prior to creating the dictionary.
thanks for your efforts. Your package is amazing
