### ISSUE TITLE
include_unknown doesn't actually include unknown words

### ISSUE THREAD

**Issue by ltmorro** [mammothb/symspellpy#30]
In lookup(), since the ```include_unknown``` flag is only included within early_exit(), it doesn't seem to work if early_exit is never called. I've had unknown words return 0 suggestions. For example, the word "cablevantage" returns nothing. It seems like including ```        if include_unknown and not suggestions:
            suggestions.append(SuggestItem(phrase, max_edit_distance + 1, 0))``` before the final sort, fixes the issue. Is this a symptom of a bigger bug, or a design choice?

**Comment by mammothb** [comment]
You're right. I misunderstood the original C# code. I have fixed this in the `dev` branch.

**Comment by ltmorro** [comment]
Cool, thanks.
