### ISSUE TITLE
Inconsistent example output

### ISSUE THREAD

**Issue by farleylai** [mammothb/symspellpy#34]
Installed 6.3.7 from pip as instructed on both latest macOS and ubuntu 16.04 and downloaded `frequency_dictionary_en_82_765.txt` from the official github.
Just ran the examples in the README.md and got inconsistent output on both platforms as follows:

## Sample usage (lookup and lookup_compound)
The last number(log_prob_sum) is **11** instead of 10.
```
members, 226656153, 1
where is to love he had dated for much of ﻿the past who couldn't read in six grade and inspired him, 300000, 11
```

## Sample usage (word_segmentation)
The first word `the` is segmented as `t` and `he` which are a bit obvious.
Also `overt he` should be `over the`.
I noticed the last two numbers are different from `8 -34.491167981910635`.
```
t he quick brown fox jumps overt he lazy dog, 10, -52.10066239535173
```
Next, I tried to segment the test string `itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomitwastheageoffoolishness` from the official site and the output shows the same error pattern of `the` as `t he`.

Any ideas?

**Comment by mammothb** [comment]
The output for `lookup_compound` in the `README.md` is outdated due to https://github.com/mammothb/symspellpy/commit/7bc16d07fcde1169a8c137afc9b7a438f6175124 fixing a bug in the distance calculation. 

However, the expected output should be (position of `distance` and `count` are swapped to match the original code)
```
where is the love he had dated for much of the past who couldn't read in sixth grade and inspired him 9 300,000
```
This is also the output given by the original code. However, it still does not match the output you have obtained (`distance=9` vs `distance=11`). I was also able to obtain the same output for the `word_segmentation` sample.

I have tested this on ubuntu 16.04 with python 3.5.2. I will try to get a macOS system to see if I can replicate the same bug.

**Comment by mammothb** [comment]
I have also tested the sample code on macOS 10.13.6 with python 3.6.1. I was able to obtain the output mentioned in the `README.md` as well. Could you try to reinstall the package to see if that helps?

**Comment by farleylai** [comment]
In case of out of dated code, the script is attached FYI:

[main.py.txt](https://github.com/mammothb/symspellpy/files/2892847/main.py.txt)

It basically combines the two example main()s to test both.
Unfortunately, the output remains even if I:
- reinstalled through pip or
- created conda envs with py3.5 and py3.6 respectively to install symspellpy 6.3.7. or
- used symspellpy by cloning the repo

Since the error pattern is around `t he`, I may check with my colleague to see if they have a similar issue.

**Comment by farleylai** [comment]
I finally figured out the cause which has nothing to do with the installation but some invisible character in the frequency dictionary that I downloaded from the original author wolfgarbe's repo:

[frequency_dictionary_en_82_765.txt](https://raw.githubusercontent.com/wolfgarbe/SymSpell/master/SymSpell/frequency_dictionary_en_82_765.txt)

Running `diff` to compare the files and it shows there is an invisible difference in line 1 that `the` coincidentally:
```
1c1
< the 23135851162
---
> ﻿the 23135851162
```

I tried to set list in vim to show the invisible difference but there seems nothing different.
How did you get the frequency_dictionary_en_82_765.txt?

**Comment by mammothb** [comment]
I see, I might have saved it as utf-8 when I was debugging the program and uploaded it as that.

[`load_dictionary`](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L178) allows you to choose the `encoding` so you could use that as well.
