### ISSUE TITLE
Allow removal of dictionary item

### ISSUE THREAD

**Issue by kakaroto** [mammothb/symspellpy#35]
Hi, great work on this! Other than the loading of the dictionary, it seems to be very fast at doing suggestions.
I like having the ability to do a `create_dictionary_entry` to add a new word to the dictionary, however, there is no `delete_dictionary_entry`. I've tried to just give a negative count for the word, but the code ignores it if count <= 0. I can probably do a `del obj._words[word]` but I assume it wouldn't be a great idea to do that without also affecting the deletes. I had a quick look at the `create_dictionary_entry` and I feel like this should be enough to delete a word ? 
```
        del self._words[key]
        # find deletes
        edits = self._edits_prefix(key)
        for delete in edits:
            delete_hash = self._get_str_hash(delete)
            self._deletes[delete_hash].remove(key)
```

**Comment by mammothb** [comment]
Implemented in https://github.com/mammothb/symspellpy/commit/00bae482a6871b8eff4e42149d5ae3e0c82629be . The `self._max_length` had to be updated as well in case we delete the longest word.
