### ISSUE TITLE
How to disable word segmentation?

### ISSUE THREAD

**Issue by mzeidhassan** [mammothb/symspellpy#36]
HI @mammothb,

Hope all is well with you.

Can you please let me know how can I disable word segmentation? Apparently, this bringing more harm than good when I test it with Arabic. It makes up undesired corrections. 

Thanks

**Comment by mammothb** [comment]
What do you mean by disable? Can you not just use other functions like `lookup` or `lookup_compound`?

**Comment by mzeidhassan** [comment]
OK, maybe I am wrong.  So, let me clarify.

I am using lookup_compound. lookup doesn't work with full sentences as far as I know, right?

In your readme file when you use 'lookup_compound', it says:

>   # lookup suggestions for multi-word input strings (supports compound
>  # splitting & merging)"

The reason I am asking is that I noticed it comes up with strange suggestions. For example"

text = "هناك إقتراحاب كتيرة في هذا الملف."

The correct output should be:

"هناك اقتراحات كثيرة في هذا الملف"

but I am getting this instead:

هناك إقتراح اب كبيرة في هذا الملف

So, it split the word "إقتراحاب" into 2 words: إقتراح and اب . 
Even both split words are not misspelled. So, I thought this is an effect of segmentation and merging. Isn't it?

**Comment by mammothb** [comment]
I don't think it is possible to disable the splitting and joining for `lookup_compound` since that is one of the primary aims of `lookup_compound`.

Is the word frequency of `إقتراح` and `اب` much higher than higher than that of `اقتراحات`? That could be one of the reason why a split result is given.

If you really want to avoid splitting, then you could pre-process your input by splitting it into individual word than the do `lookup` for them individually.

**Comment by mzeidhassan** [comment]
The word اقتراحات has this frequency number:
اقتراحات 12201

while إقتراح has this number:
إقتراح 73
and اب:
اب 1777

I think I need to clean up my dictionary because the last word shouldn't even exist, but my main issue now is why symspellpy decided to split the word into 2 words with lower frequency than the main and word اقتراحات which has really high frequency.

One last question about the dictionary creation:

What is the best approach to create the dictionary? Should you use perfect text that has no spelling mistakes at all or is it better to use text that has mixed correct and wrong spellings with more correct spellings than wrong ones?

**Comment by mammothb** [comment]
I think you should use perfect text when creating dictionary. Since if your dictionary contains wrong spellings, your input could be "corrected" into those wrong spellings

**Comment by mzeidhassan** [comment]
Thanks for the advice!
I did one more testing with `lookup`.
I check only for "إقتراحاب". 

it returned "إقتراحات" which has a frequency number of 9, and it didn't return the correct one 'اقتراحات' which has a frequency number of '12201'. 

I even changed this line of code from 'ClOSEST", to "TOP", but I still get the same result:
`suggestion_verbosity = Verbosity.TOP`

I am not sure what is causing this. Any idea?

**Comment by mammothb** [comment]
The suggestions are sorted by `edit_distance` first and then by `count_frequency`. https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L283

Since `إقتراحات` has an edit distance of 1 and `اقتراحات` has an edit distance of 2, `إقتراحات` is returned instead.

**Comment by mzeidhassan** [comment]
Hi @mammothb ,
Sorry to reopen this issue.
How can I change the logic of smyspellpy and make it get suggestions sorted by count_frequency first, then edit_distance? 
Thanks!

**Comment by mammothb** [comment]
Swapping `count` and `distance` [here](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L928) should work.

```python
    def __eq__(self, other):
        """Order by distance ascending, then by frequency count
        descending
        """
        if self._count == other.count:
            return self._distance == other.distance
        else:
            return self._count == other.count

    def __lt__(self, other):
        if self._count == other.count:
            return self._distance > other.distance
        else:
            return self._count < other.count
```

**Comment by mzeidhassan** [comment]
Hi @mammothb ,

I am sorry for keeping adding to this thread, but I think it's still relevant, and it's better than creating a new issue.

I would like to understand how to control the corrections. For example, look at the attached screen shot.
![image](https://user-images.githubusercontent.com/7589948/56482045-46070480-647f-11e9-8312-d626de21b200.png)

The right spelling for the misspelled word 'وثائقى' is the second in the screen shot 'وثائقي'. 
I understand that the edit distance for the first and second corrections is 1, and the first one has a higher number of occurrences, hence it was chosen, although the second form is very close to the word. Is there a way to control this behavior? 
Thanks in advance for your support!

**Comment by mammothb** [comment]
Is this similar to wanting `sream` to be corrected to `steam` instead of `stream` because it fits the context of the text? If so, I don't think it's possible since the package cannot choose a correction based on context.

**Comment by mzeidhassan** [comment]
In Arabic, we have 2 close characters in terms of shape
ى and ي (note the 2 dots below the latter) . So, the current word is وثائقى which should be corrected to وثائقي (i.e., replace the letter without 2 dots with the one with 2 dots below).

Since the edit distance is the same, the preference goes to the one with higher frequency. I am not sure how to tackle this problem. 

Symspellpy decided to go with the deletion of the last character in the word, not replacing it with the correct one (ي). Is there a way to give preference to replacement over deletion? 

Thanks again for your continuous support!

**Comment by mammothb** [comment]
In that case, can you not just select the first result with the same length as the original (incorrect) word?

**Comment by mzeidhassan** [comment]
This is brilliant, @mammothb ! It worked perfectly fine for that example. Thank you so much for your amazing support.
