### ISSUE TITLE
Why is Numpy used?

### ISSUE THREAD

**Issue by emiatej9** [mammothb/symspellpy#43]
Thank to read my issue, and I use symspellpy gratefully.

I wonder why the numpy library is used to generate arrays for the sake of storing costs in every step.

Is there any problem if native arrays were used?
(It's just a question... not serious)

thianks.

**Comment by mammothb** [comment]
Initially, I thought I would require to do some vector operations and did not change back since the difference in performance was not that great (did not test this in detail)
