### ISSUE TITLE
Hash table collision check is not necessary

### ISSUE THREAD

**Issue by workingenius** [mammothb/symspellpy#44]
Python dict handles hash collision (two different keys can have different values even if their hash equal). [This article](https://www.laurentluce.com/posts/python-dictionary-implementation/ ) makes it clear.

Thus, logic about hash collision checking is not necessary, and code will be simplified. 

Thank you

**Comment by mammothb** [comment]
Removed hash collision check in https://github.com/mammothb/symspellpy/commit/44bd7e156d3ee4159e1c836971383c441d64952b
