### ISSUE TITLE
Carrying over casing

### ISSUE THREAD

**Issue by zoltan-fedor** [mammothb/symspellpy#45]
Hi,
For my project I am implementing an extension to allow me to carry over the casing (eg uppercase vs lowercase characters) from the input phrase to the typoe-corrected case.

For example:
"I have a typo prooblem in Neew York"
currently turns into
"i have a typo problem in new york"

But I will make it to be:
"I have a typo problem in New York"

I am wondering whether you would be interested in a pull request for it, knowing that this is a port of https://github.com/wolfgarbe/SymSpell.

**Comment by mammothb** [comment]
Please do, I think it's a requested feature for the main project as well (https://github.com/wolfgarbe/SymSpell/issues/34).

**Comment by zoltan-fedor** [comment]
I have created a PR for it - see https://github.com/mammothb/symspellpy/pull/46
