### ISSUE TITLE
Handling Specific Contractions

### ISSUE THREAD

**Issue by chrisyue1998** [mammothb/symspellpy#47]
I noticed that symspellpy gives some contractions as suggestions (e.g. "can't"), but when I try to produce suggestions for the word "isn't," for example, it gives me "int." Any ideas as to how I could fix this?

**Comment by mammothb** [comment]
If you look at the last few lines of `frequency_dictionary_en_82_765.txt`, it contains some common contractions but "isn't" is not included. You can manually add it to the dictionary file or use the `create_dictionary_entry` method.
