### ISSUE TITLE
Transfer Casing argument not found

### ISSUE THREAD

**Issue by d-v-dlee** [mammothb/symspellpy#52]
Hi,

I've downloaded the symspellpy package both directly from github and using pip install as directed and I'm not seeing the transfer_casing boolean. I know that it was added a month ago or so, do you have any suggestions on how I could make that work? 

Appreciate it.

**Comment by mammothb** [comment]
Sorry, I forgot to publish the changes. It should be fixed now, just update package and you should be able to use the `transfer_casing` argument.

**Comment by d-v-dlee** [comment]
Appreciate it!
