### ISSUE TITLE
Facing some issues with ignore_non_words

### ISSUE THREAD

**Issue by AnandDev8** [mammothb/symspellpy#54]
Hi,

I am currently working on a chat bot use case where i found symspellpy very useful but i am facing some issues with "ignore_non_words" parameter of lookup_compound.
I need a specific pattern like an account no xx004453 to be ignored by spell checker and it kinda of works as well.
### My regex is made to satisfy patterns like starts with 2 or 3 alphabets and then numbers or hyphens.
My issue is as follows
* je3453 -> **jeff hi**  (it is converting these numbers)[Happens to small numbers only like xx123]
* xx1234-5678-1234 -> **xx1234 5678 1234**  (all the '-' are removed)

How to solve these issue ?

**Comment by mammothb** [comment]
`ignore_non_words` is a boolean flag, regex is used for `ignore_token` which is available for `lookup` and `word_segmentation`. In your case, could you do some preprocessing and filter out the words which match your regex pattern before feed them into symspellpy?
