### ISSUE TITLE
Default to \t split when creating dictionary

### ISSUE THREAD

**Issue by shahanesanket** [mammothb/symspellpy#56]
Currently when the dictionary is loaded from a txt file it is split on space. Using \t as default split would allow to add the n-gram phrases directly via a file. It will helpful to do by just adding a dictionary text file with lots of phrases. Adding an option to specify the split char will be helpful too.

**Comment by mammothb** [comment]
Implemented in https://github.com/mammothb/symspellpy/commit/b2bcdfdd34dfe00ff8522fe74180ebc885ea7583. But "space" was set as the default separator to avoid breaking existing code.
