### ISSUE TITLE
Failed to create dictionary for chinese corpus!!

### ISSUE THREAD

**Issue by VJAYSLN** [mammothb/symspellpy#63]
Hello @mammothb , I am using symspellpy for a last couple of months. I am trying to create dictionary with Chinese  corpus dataset. But it just split words from text by using space. (just like english corpus)
BTW, we shouldn't do that for Chinese corpus. Is there any alternative way for create frequency dictionary for chinese corpus ?
Thanks in Advance : )

**Comment by mammothb** [comment]
You can create your own custom script to parse the Chinese corpus and save it in either the default python dictionary (to be read with `load_dictionary_stream`) or a text file (to be read with `load_dictionary`).
