### ISSUE TITLE
Is Symspell Thread Safe?

### ISSUE THREAD

**Issue by hadyan-tvlk** [mammothb/symspellpy#64]
Hi @mammothb,

I try to deploy symspell model in multi-threading config using simple flask API. When we're trying to validate the result several times, turns out the result is not consistent (yield different result after test several times).

I have feeling that symspell is not thread safe. So, i tested it using single thread. And the result now consistent.

Is my hypothesis true? Related [article](https://github.com/wolfgarbe/SymSpell/issues/24) for safe thread issue.

Thanks!

**Comment by mammothb** [comment]
Yes, I think symspellpy is not thread safe since it's passing the member variable as a parameter ([code](https://github.com/mammothb/symspellpy/blob/master/symspellpy/editdistance.py#L155)). I'll look into making it thread safe.

**Comment by mammothb** [comment]
@hadyan-tvlk could you please provide a sample code where symspellpy yields inconsistent result when using multi-threading config with flask API?

**Comment by hadyan-tvlk** [comment]
Hi @mammothb, sorry for the late response. Which part of the code do you exactly need for test (this is for testing purpose, right?)?

**Comment by hadyan-tvlk** [comment]
I

**Comment by hadyan-tvlk** [comment]
I hope this code can help:

```python

from symspellpy import Verbosity, SymSpell

unigram_obj = SymSpell(3, 5, count_threshold=5)

unigram_obj.load_dictionary("/tmp/symspell-model/unigrams.dict", term_index=0,count_index=1, encoding="utf-8")

sample_word_input = "cafe"

unigram_obj_lookup_res = unigram_obj.lookup(sample_word_input, Verbosity.CLOSEST, 2)

unigram_obj_candidates = [j.term for j in unigram_obj_lookup_res]

# these candidate result can be different for similar `sample_word_input`
print(unigram_obj_candidates)
```

**Comment by mammothb** [comment]
I am not too familiar with multi-threading with flask and setting a test to replicate the error you observe.

I have this code from a threading code sample but I am not able to replicate the error.

```python
import threading

import pkg_resources
from symspellpy import SymSpell, Verbosity

def thread_function(symspell):
    for __ in range(1000):
        input_term = "whereis"
        correction = ['whereas', 'wherein', 'wheres']
        suggestions = symspell.lookup(input_term, Verbosity.CLOSEST, 2)
        candidates = [suggestion.term for suggestion in suggestions]

        if candidates != correction:
            print(candidates)

if __name__ == "__main__":
    sym_spell = SymSpell(3, 5, count_threshold=5)
    dictionary_path = pkg_resources.resource_filename(
        "symspellpy", "frequency_dictionary_en_82_765.txt")
    sym_spell.load_dictionary(dictionary_path, term_index=0, count_index=1)

    threads = list()
    for index in range(24):
        x = threading.Thread(target=thread_function, args=(sym_spell,))
        threads.append(x)
        x.start()

    for thread in threads:
        thread.join()
```

So I was wondering if you had a sample code (preferably without having to set up flask) to replicate the error.

**Comment by hadyan-tvlk** [comment]
This is the tricky part. When i test it in local environment (my laptop), everything's ok. When i deploy it to the actual server, that's when the problem appear.

**Comment by mammothb** [comment]
I have pushed some changes to the `dev-threadsafe` branch, could you try and see if that fixes your problem?

**Comment by hadyan-tvlk** [comment]
Noted, let me try it first

**Comment by hadyan-tvlk** [comment]
@mammothb After test it several times, it seems the `dev-threadsafe` branch solve the problem. I didn't saw any issue again.

However, i saw latency increase compared to current branch. is it expected?

**Comment by mammothb** [comment]
It is possible, since we're creating a new array every time we do a distance comparison in the thread safe version ([code](https://github.com/mammothb/symspellpy/blob/dev-threadsafe/symspellpy/editdistance.py#L160))

**Comment by hadyan-tvlk** [comment]
Wait, why you're referring to [line 160](https://github.com/mammothb/symspellpy/blob/dev-threadsafe/symspellpy/editdistance.py#L160) instead of [line 153](https://github.com/mammothb/symspellpy/blob/dev-threadsafe/symspellpy/editdistance.py#L153)?

Since the safe thread enabled when `is_thread_safe` True

**Comment by mammothb** [comment]
Sorry, I selected the wrong line by mistake.

**Comment by hadyan-tvlk** [comment]
It's so unfortunate the fix will increase the latency where it's really matter to have fast computation.

Right now, we did workaround to manage thread issue with add locking mechanism to the model. We have feeling the solution should be reliable. What do you think?

**Comment by mammothb** [comment]
The locking mechanism offers lower latency compared to the solution on `dev-threadsafe` branch? If you'd like to, you could submit a PR for it.

**Comment by hadyan-tvlk** [comment]
The locking not happen in the symspell, instead on the flask component. The latency increase can take ~2x than stable branch
