### ISSUE TITLE
How Verbosity::Closest is Faster than Verbosity::Top?

### ISSUE THREAD

**Issue by VJAYSLN** [mammothb/symspellpy#65]
Hi @mammothb ,
I am using `symspell` for a last couple of months. It works awesome. I am working with a large corpus for different languages. In my point of view, Top will always give exactly one correction, And Closest will give one or more corrections. So, what was the reason, `Verbosity::Top` is slower than `Verbsity::Closes`t?

**Comment by mammothb** [comment]
Do you have a sample code to benchmark this behavior? I have briefly tried on my system and I'm getting inconsistent results.

**Comment by VJAYSLN** [comment]
#actual_sentences, errored_sentences lists, having gold and errorneous sentences respectively.
sym_spell = SymSpell(2,7)
if not sym_spell.load_dictionary("./chinese_2m.dict.txt",0,1):
    print("Not Found...")
start = time.time()
for sentence in errored_sentences):
  # sentence = ["我们", "栽歌", "栽舞", "欢庆", "新", "一年", "到来"]
    for word in sentence:
         cands = sym_spell.lookup(word, Verbosity:TOP, 2) #Or Verbosity:CLOSEST
         if len(cands):
            for cand in cands:
               correct_words.append(cand.term)
        else:
            correct_words.append(word)
    correct_sent.append(correct_words)
print(time.time() - start)

**Comment by mammothb** [comment]
It might be possible that repeatedly accessing the element in the `suggestions` list ([code](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L634)) slows it down in some cases.
