### ISSUE TITLE
Is there a parameter like Verbosity for lookup_compound, it always return one result

### ISSUE THREAD

**Issue by KienPM** [mammothb/symspellpy#69]
When I tried lookup_compound, it always return one result. Is there any problem?
I attached my dictionaries, below is my test code
```
from symspellpy import SymSpell, Verbosity

sym_spell = SymSpell(max_dictionary_edit_distance=2, prefix_length=7)
dictionary_path = "frequency_dict.txt"
bigram_path = "bi_gram_frequency_dict.txt"
# term_index is the column of the term and count_index is the
# column of the term frequency
if not sym_spell.load_dictionary(dictionary_path, term_index=0, count_index=1):
    print("Load fail")
if not sym_spell.load_bigram_dictionary(bigram_path, term_index=0, count_index=2):
    print("Load fail")

# lookup suggestions for multi-word input strings (supports compound splitting & merging)
input_term = "soạn bài sọ dùa"
# max edit distance per lookup (per single word, not per whole input string)
suggestions = sym_spell.lookup_compound(input_term, max_edit_distance=2)
# display suggestion term, edit distance, and term frequency
for suggestion in suggestions:
    print(suggestion)
```
Output
```
soạn bài sọ mùa, 1, 0
```
I'd like to get other results such as ```soạn bài sọ dừa```
[bi_gram_frequency_dict.txt](https://github.com/mammothb/symspellpy/files/4019352/bi_gram_frequency_dict.txt)
[frequency_dict.txt](https://github.com/mammothb/symspellpy/files/4019353/frequency_dict.txt)

**Comment by wolfgarbe** [comment]
There is no Verbosity parameter for lookup_compound, because the currently used algorithm doesn't scale for longer strings, if all possible variants are calculated. I tested this, but the computational complexity increased dramatically, and the lookup time became unbearable.

**Comment by KienPM** [comment]
Thank you for your answer sir!
I also tried lookup with verbosity set to ALL, but there is no result. Can you help me please!

**Comment by mammothb** [comment]
Are you using `lookup` for `soạn bài sọ dùa` to try and get `soạn bài sọ dừa`? If so, it will not work since `lookup` will only try correct input terms as a whole to what is inside `frequency_dict.txt` and your `frequency_dict.txt` only contains single terms.

**Comment by KienPM** [comment]
Oh, I got it, thank you so much!
