### ISSUE TITLE
Punctuations getting removed

### ISSUE THREAD

**Issue by rushdishams** [mammothb/symspellpy#7]
Hello. Great work!

For inputs with punctuations, `There are many novel, innovaive, and empirical anayysis availaible.` we get outputs like `there are many novel innovative and empirical analysis available`. Is it possible to keep the punctuations?

**Comment by mammothb** [comment]
I don't think it's possible right now since `lookup_compound` will try to join words together to get the right word and therefore needs to strip all punctuations. You could try to split your input phrase at the punctuations and then feed that into `lookup_compound` but I'm not sure how that will affect the accuracy.

**Comment by duhaime** [comment]
It's a shame this is closed--keeping punctuation is pretty vital to the integrity of language...

**Comment by Raghu17s** [comment]
Any updates on punctuations?

**Comment by duhaime** [comment]
I needed to keep punctuation in some documents I was processing and used the following:

```python
import pkg_resources, string
from symspellpy import SymSpell, Verbosity

spell = SymSpell(max_dictionary_edit_distance=2, prefix_length=7)
dictionary_path = pkg_resources.resource_filename('symspellpy', 'frequency_dictionary_en_82_765.txt')
spell.load_dictionary(dictionary_path, term_index=0, count_index=1)

def correct(w):
  word = w
  o = spell.lookup(w,
    Verbosity.CLOSEST,
    max_edit_distance=2,
    transfer_casing=True)
  if not o: return w
  word = o[0].term
  if w[0].isupper():
    word = word[0].upper() + ''.join(word[1:])
  # find start punctuation
  start_idx = 0
  start_punct = ''
  while w[start_idx] in string.punctuation:
    start_punct += w[start_idx]
    if start_idx + 1 < len(w):
      start_idx += 1
    else:
      break
  # find end punctuation
  end_idx = 1
  end_punct = ''
  while w[-end_idx] in string.punctuation:
    end_punct += w[-end_idx]
    if end_idx - 1 > 0:
      end_idx -= 1
    else:
      break
  return start_punct + word + end_punct

s = '''Now that we have carried our geographical analogy quite far, we return to the uestion of isomorphisms between brains. You might well wonder why this whole uestion of brain isomorphisms has been stressed so much. What does it matter if two rains are isomorphic, or quasi-isomorphic, or not isomorphic at all? The answer is that e have an intuitive sense that, although other people differ from us in important ways, hey are still "the same" as we are in some deep and important ways. It would be nstructive to be able to pinpoint what this invariant core of human intelligence is, and hen to be able to describe the kinds of "embellishments" which can be added to it, aking each one of us a unique embodiment of this abstract and mysterious quality alled "intelligence".'''
cleaned = ' '.join([correct(w) for w in s.split()])
print(cleaned)
```

That prints:

```
Now that we have carried our geographical analogy quite far, we return to the question of isomorphisms between brains. You might well wonder why this whole question of brain isomorphisms has been stressed so much. What does it matter if two rains are isomorphic, or quasi-isomorphic, or not isomorphic at all? The answer is that a have an intuitive sense that, although other people differ from us in important ways, hey are still "the same" as we are in some deep and important ways. It would be instructive to be able to pinpoint what this invariant core of human intelligence is, and hen to be able to describe the kinds of "embellishments" which can be added to it, making each one of us a unique embodiment of this abstract and mysterious quality called "intelligence".
```

**Comment by 18goldr** [comment]
@duhaime the only issue with your code is that if a symbol is surrounded by whitespace, then it will try to spell check that. For example, the sentence `test - tst` will output `test -a- test`. To fix this, I simply add `if w in string.punctuation: return w` to the beginning of `correct(w)`.

**Comment by 18goldr** [comment]
@duhaime One issue with your code is that if a symbol is surrounded by whitespace, then it will try to spell check that. For example, the sentence `test - tst` will output `test -a- test`. To fix this, I simply check if all characters in a string are alphabetical at the beginning of the function.

Another issue I have found is if you give the string `No,` the code will output `Not` rather than `No`. To fix this, I remove all  all punctuation form the string and replace them with spaces. I then run the algorithm recursively on the different parts. 

The only issue I can find with my version of the algorithm is that it will spellcheck words like `un-do` to `in do` rather than `undo`. This is because I replace punctuation by spaces, which makes sense for certain cases like `all-knowing` but not cases like `un-do`. To fix this, I check if, when combined, the two parts of the word form an english word or not.

Here is the full code (note - `word_list` is the list of words in a language):
```
def correct(w):
    if all([not c.isalpha() for c in w]): return w
    
    word = w
    
    # Fix for strings with punctuations in them
    # Otherwise, it will try to spellcheck with the punctuation included which messes up results
    word_no_punc = w.translate(str.maketrans(string.punctuation, ' '*len(string.punctuation)))
    split = word_no_punc.split()
    l = len(split)
    if l > 1:
        corrected = []
        i = 0
        while i < l:
            if i == l-1:
                corrected.append(correct(split[i]))
                break
        
            # if the words combined are english, then consider it as one word
            tmp = split[i] + split[i+1]
            if tmp in english_vocab:
                corrected.append(tmp)
                i += 1
            else:
                # otherwise, spellcheck them separately
                corrected.append(correct(split[i]))
            i += 1
        return corrected
    else:
        word_no_punc = word_no_punc.strip()
    
    o = sym_spell.lookup(word_no_punc,
        Verbosity.CLOSEST,
        max_edit_distance = 2,
        transfer_casing = True)
    
    if not o: return w

    word = o[0].term
    if w[0].isupper():
        word = word[0].upper() + ''.join(word[1: ])
    
    # find start punctuation
    start_idx = 0
    start_punct = ''
    while w[start_idx] in string.punctuation:
        start_punct += w[start_idx]
        if start_idx + 1 < len(w):
            start_idx += 1
        else :
            break
    
    # find end punctuation
    end_idx = 1
    end_punct = ''
    while w[-end_idx] in string.punctuation:
        end_punct += w[-end_idx]
        if end_idx - 1 > 0:
            end_idx -= 1
        else:
            break
    return start_punct + word + end_punct

def spellcheck_keep_punctuation(sentence):
    corrected = []
    for word in sentence.split():
        corrected_word = correct(word)
        if isinstance(corrected_word, list):
            corrected.extend(corrected_word)
        else:
            corrected.append(corrected_word)
            
    return ' '.join(corrected)
```

**Comment by xniche** [comment]
@18goldr thanks for sharing the function - it works pretty well! have a what might be a dumb question on `english_vocab` - it is not defined within the function, but I have no issues running `spellcheck_keep_punctuation(sentence)`.

however when I unwrap the function, I run into error prompts stating `english_vocab` is not defined. why then does it work within the function, even though it's not explicitly defined within it?

**Comment by alvesman** [comment]
My phrase spell checker preserving punctuation:

import re
word_split = re.compile(r"[^\W]+", re.U)

def spell_corrected(term):
    suggestions = sym_spell.lookup_compound(
        term, 
        max_edit_distance=2,         # The maximum edit distance between input and suggested words.
        ignore_non_words=True,       # numbers and acronyms are left alone
        split_phrase_by_space=True,  # otherwise hyphen words will be split https://github.com/wolfgarbe/SymSpell/issues/85
        ignore_term_with_digits=True # any term with digits is left alone
    )
    # Splitting errors, concatenation errors, substitution errors, transposition errors, deletion errors and insertion errors
    # can by mixed within the same word.
    
    corrected = suggestions[0].term # [:2][0].term
    # This combined with split_phrase_by_space=True would be enough just to spell check
    # but punctuation is lost.
    
    # The spell check is already done in 'corrected'. Now we just want to keep the punctuation.
    in_list = word_split.findall(term)
    chk_list = word_split.findall(corrected)
    
    # To keep ponctuation we take the original phrase and do  word by word replacement
    out_term = term
    word_count = 0
    for word in in_list:
        out_term = out_term.replace(word, chk_list[word_count])
        word_count += 1

    return out_term
