### ISSUE TITLE
Composition' object has no attribute 'lower'

### ISSUE THREAD

**Issue by srijiths** [mammothb/symspellpy#71]
When i tried to use lookup_compound on a text extracted from a PDF, its getting an exception.

```
  suggestions = self.symspell_correction.lookup_compound(result, 2)
  File "D:\softwares\anaconda3\lib\site-packages\symspellpy\symspellpy.py", line 706, in lookup_compound
    term_list_1 = helpers.parse_words(phrase)
  File "D:\softwares\anaconda3\lib\site-packages\symspellpy\helpers.py", line 135, in parse_words
    return re.findall(r"([^\W_]+['’]*[^\W_]*)", phrase.lower())
AttributeError: 'Composition' object has no attribute 'lower'
```

My code is written in this way

```
result = self.symspell_wordsegment.word_segmentation(text)
suggestions = self.symspell_correction.lookup_compound(result, 2)
```

Thank You
Srijith

**Comment by mammothb** [comment]
`word_segmentation` returns a Composition ([doc](https://symspellpy.readthedocs.io/en/latest/api/symspellpy.html#symspellpy.symspellpy.SymSpell.word_segmentation)). And `lookup_compound` only accepts `string` as the `phrase` type ([doc](https://symspellpy.readthedocs.io/en/latest/api/symspellpy.html#symspellpy.symspellpy.SymSpell.lookup_compound)). So you will need to pass either the `segmented_string` or the `corrected_string` to `lookup_compound` ([doc](https://symspellpy.readthedocs.io/en/latest/api/symspellpy.html#symspellpy.symspellpy.Composition)).

**Comment by srijiths** [comment]
@mammothb Thank you very much for a quick reply. I solved it by taking **result.corrected_string** 
Thank You
