### ISSUE TITLE
How to apply for non-Eng text

### ISSUE THREAD

**Issue by Wickky** [mammothb/symspellpy#75]
Is there any way that I can apply this to other languages as well?

**Comment by adocampo** [comment]
Yes, I also would like to know if there are support for other major languages like spanish

**Comment by mammothb** [comment]
You will need to use a frequency dictionary for the desired language. The rest of the code should remain the same. If you have trouble creating your own frequency dictionaries, the original project has some available [here](https://github.com/wolfgarbe/SymSpell/tree/master/SymSpell.FrequencyDictionary).
