### ISSUE TITLE
word.segmentation results in StopIteration 

### ISSUE THREAD

**Issue by aastha19** [mammothb/symspellpy#76]
Hi

I wish to run the word segmentation command using my own dictionary. The dictionary is loaded properly but when the "sym_spell.word_segmentation(input_term)" command is run, it returns in the following error:

![image](https://user-images.githubusercontent.com/14852345/78546258-bdfa4600-781a-11ea-96d2-ed43f319dcb0.png)

What might be the reason for this? And also how to solve this?

**Comment by mammothb** [comment]
Can you share the code and dictionary used so I can replicate the error and debug?

**Comment by aastha19** [comment]
@mammothb this has been resolved. The dictionary had a problem

**Comment by DamienJacquemart** [comment]
Hi @aastha19,

I'm running the same issue. What did you fix in your dictionary ?

Thanks !

**Comment by aastha19** [comment]
Hi @DamienJacquemart 

I had created the dictionary using some other method and was trying to load it in SymSpell. 

To resolve this error I simply used Symspell's functionality (sym_spell.create_dictionary(corpus_path)) and saved it as a pickle file so that it could also be used for future purposes. 

Using SymSpell's functionality helped me resolve the error as the dictionary created earlier was improper.

**Comment by DamienJacquemart** [comment]
Thank you @aastha19 for sharing your experience ! It's helpful.

Best,
Damien

**Comment by ByUnal** [comment]
@aastha19 @mammothb I have dictionary that I want to use in SymSpell instead of default unigram and bigram dictionary
![image](https://user-images.githubusercontent.com/43930582/145214051-fb47c3d3-da2f-437a-9d4b-20b520fdf9cd.png)

I have my own dictionary in "data" folder, but It didn't work as you said. How can I fix this ?
