### ISSUE TITLE
I can not understand the cause of the error

### ISSUE THREAD

**Issue by MedStock** [mammothb/symspellpy#8]
I'm trying to run your example...
...
from symspellpy.symspellpy import SymSpell, Verbosity  # import the module
...
and I get an error for the import line:
ModuleNotFoundError: No module named 'symspellpy.symspellpy'; 'symspellpy' is not a package

**Comment by mammothb** [comment]
Did you install the package using `pip install -U symspellpy`? If you did, try using
```from symspellpy import SymSpell, Verbosity```

Both import commands worked on my machine.

**Comment by mammothb** [comment]
When you do `pip freeze | grep symspellpy`, do you see the output `symspellpy==6.3.1`? You should see that if the package is installed properly.

A possible workaround is to copy the repository into your project directory, instructions can be found on an older version of [README.md](https://github.com/mammothb/symspellpy/blob/c10b10bb00c103b9e0820d35901d20057e8a072c/README.md)
