### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by PickJBennett** [mammothb/symspellpy#83]
Hello, I pasted `python -m pip install -U symspellpy` according to https://symspellpy.readthedocs.io/en/latest/users/installing.html into my Terminal and was given the following errors:

Collecting symspellpy
ERROR: Could not find a version that satisfies the requirement symspellpy (from versions: none)
ERROR: No matching distribution found for symspellpy

I'm using macOS Mojave, version 10.14.6 (18G103) and Python version 2.7.10

Is there anything else I can do to install this? Thank you!

**Comment by mammothb** [comment]
Currently only Python >= 3.4 is officially supported, there is an [old thread](https://github.com/mammothb/symspellpy/issues/11) about manually installing symspellpy for Python 2, perhaps that could help.
