### ISSUE TITLE
Not work ignore_any_term_with_digits in google.colab

### ISSUE THREAD

**Issue by grekys84** [mammothb/symspellpy#85]
Hello. I get this error when trying to use the parameter "ignore_any_term_with_digits=True".
"lookup_compound() got an unexpected keyword argument 'ignore_any_term_with_digits'"
The task is to leave the abbreviations containing unchanged "/". What am I doing wrong?

**Comment by mammothb** [comment]
Hi, sorry about that, I think there is a typo with the documentation. the argument name should be `ignore_term_with_digits`. I'll fix the documentation soon.

**Comment by grekys84** [comment]
Thank you very much. Everything works now.
