### ISSUE TITLE
Inconsistent Ouptut for lookup_compound across windows systems

### ISSUE THREAD

**Issue by saurabhbh21** [mammothb/symspellpy#88]
I have installed symspellpy==6.7.0 in two of my windows system in conda environment, the output in both the system is different for output_compound method (with the same input text).

The code used is the one mentioned in this link: https://symspellpy.readthedocs.io/en/latest/examples/lookup_compound.html#keep-original-casing

Any help in fixing will be really appreciated. Thanx.

**Comment by mammothb** [comment]
May I know what are the different outputs produced?
