### ISSUE TITLE
Provide create dictionary example

### ISSUE THREAD

**Issue by caionakai** [mammothb/symspellpy#9]
Could you provide an example creating a new dictionary?

**Comment by mammothb** [comment]
As in create something like `frequency_dictionary_en_82_765.txt`? Or simply adding new entries or custom words?

If it is the latter, you can do it two ways,
  1. Use the `create_dictionary_entry()` method similar to this [unittest](https://github.com/mammothb/symspellpy/blob/master/test/test_symspellpy.py#L28).
  2. Create a custom text file with 2 columns `term` and `count` and load that using `load_dictionary()`

If it is the former, I don't have any experience with that but you can follow what the [original creator](https://github.com/wolfgarbe/SymSpell) of this program did. [Link](https://github.com/wolfgarbe/SymSpell#frequency-dictionary)

**Comment by caionakai** [comment]
Just adding new entries, thank you for your reply I think I understood how this works

**Comment by mammothb** [comment]
@MedStock I believe it's because of the wrong default encoding was use by `open()`. I have made an update and added an `encoding` option to `load_dictionary`, and I have managed to load the dictionary containing the following words when I set encoding to "utf-8":
```
АБИ 10
И 1
Б 2

**Comment by MedStock** [comment]
Thanks for the tip.
I will try to use it. But I could solve the problem when I saved the dictionary in win1251 format and used a space as a separator.
I want to thank for your decision, the speed of work and the quality level shocked me :)
Up to this point I used gensim. But your solution is easier for tasks that do not require retraining of a model for word correction.
