### ISSUE TITLE
Keep spacing in between words and not split on white space

### ISSUE THREAD

**Issue by Amokstakov** [mammothb/symspellpy#90]
Is it possible to handle/populate a dictionary with:
'air conditioning' ?

If so can you show example?

Current approach:
`            ss = SymSpell(max_dictionary_edit_distance=4)
            ss.create_dictionary(domain_corpus)
`

domain_corpus is a list containing items with spacing in between but create_dictionary splits them on white space.

**Comment by mammothb** [comment]
You can keep white spaces between words when creating a dictionary by using a custom separator as shown in https://symspellpy.readthedocs.io/en/latest/examples/dictionary.html#load-frequency-dictionary-with-custom-separator
