### ISSUE TITLE
is_acronym only detects numbers if match_any_term_with_digits

### ISSUE THREAD

**Issue by garrettargenna** [mammothb/symspellpy#91]
If match_any_term_with_digits is set to True, then the function will only check for numbers without also checking for all caps.  The doc string suggests and/or methodology

**Comment by mammothb** [comment]
@garrettargenna  Thanks for point that out, that might have been an uncaught bug. Just to confirm, the expected output based on the document should be:
| word | `match_any_term_with_digits` | output |
| - | - | - |
| ABCDE | False | True |
| AB12E | False | True |
| abcde | False | False |
| ABCde | False | False |
| abcDE | False | False |
| abCDe | False | False |
| abc12 | False | False |
| ab12e | False | False |
| ABCDE | True | True |
| AB12E | True | True |
| abcde | True | False |
| ABCde | True | False |
| abcDE | True | False |
| abCDe | True | False |
| abc12 | True | True |
| ab12e | True | True |

Do you have any other use cases or input word that you would like to be included in the tests as well?
