### ISSUE TITLE
Does SymSpell has spell checker ?

### ISSUE THREAD

**Issue by ByUnal** [mammothb/symspellpy#98]
Is there any functionality that can clarify whether given input is misspelled or not. If it is misspelled, then it should return false. It is very easy to do with given ngram dictionary.  As far as I can see, it seems there are somethings going on about this purpose, but I couldn't figure it out completely :) Can you help me about this ?

**Comment by mammothb** [comment]
Can you elaborate a bit on what kind of input are you planning to use, e.g., single word, phrase, or an entire sentence?

symspellpy does not explicit provide methods/functions to check if the input is misspelled or not, but those functionality can be built on the output given by symspellpy. I think this is in line with what the original creator intended (https://github.com/wolfgarbe/SymSpell/issues/25#issuecomment-374167995).

I can think of 2 possible approaches building up the examples given in the documentation.
- For single words, set `max_edit_distance=0` so we are looking for exact matches from the dictionary. With `verbosity=Verbosity.TOP` and `include_unknown=False`, `lookup()` will essentially return:
  - 1 result if there is a exact match (correct spelling)
  - 0 result if there is no match (misspelled)
```python
import pkg_resources

from symspellpy import SymSpell, Verbosity

sym_spell = SymSpell(max_dictionary_edit_distance=2, prefix_length=7)
dictionary_path = pkg_resources.resource_filename(
    "symspellpy", "frequency_dictionary_en_82_765.txt"
)
# term_index is the column of the term and count_index is the
# column of the term frequency
sym_spell.load_dictionary(dictionary_path, term_index=0, count_index=1)

# lookup suggestions for single-word input strings
input_term = "memebers"  # misspelling of "members"
# max edit distance per lookup
# (max_edit_distance_lookup <= max_dictionary_edit_distance)
suggestions = sym_spell.lookup(input_term, Verbosity.TOP, max_edit_distance=0)
print(len(suggestions))  # 0

input_term_2 = "members"
# max edit distance per lookup
# (max_edit_distance_lookup <= max_dictionary_edit_distance)
suggestions = sym_spell.lookup(input_term_2, Verbosity.TOP, max_edit_distance=0)
print(len(suggestions))  # 1
```

- For a phrase, symspellpy has the `replaced_words` property which contains a `dict` of misspellings and their corrected version. This can also include splitting up words such as from "hehad" to "he had". By checking the length `replaced_words`, we can determine if there was any misspelled words from the original phrase. *Note: the content of `replaced_words` is not cleared between lookup_compound() calls, so you might need to clear it manually.*
```python
import pkg_resources

from symspellpy import SymSpell

sym_spell = SymSpell(max_dictionary_edit_distance=2, prefix_length=7)
dictionary_path = pkg_resources.resource_filename(
    "symspellpy", "frequency_dictionary_en_82_765.txt"
)
bigram_path = pkg_resources.resource_filename(
    "symspellpy", "frequency_bigramdictionary_en_243_342.txt"
)
# term_index is the column of the term and count_index is the
# column of the term frequency
sym_spell.load_dictionary(dictionary_path, term_index=0, count_index=1)
sym_spell.load_bigram_dictionary(bigram_path, term_index=0, count_index=2)

# lookup suggestions for multi-word input strings (supports compound
# splitting & merging)
input_term = (
    "where is the love he had dated for much of the past who "
    "couldn't read in sixth grade and inspired him"
)
# max edit distance per lookup (per single word, not per whole input string)
suggestions = sym_spell.lookup_compound(input_term, max_edit_distance=2)
# display suggestion term, edit distance, and term frequency
for suggestion in suggestions:
    print(suggestion)

print(len(sym_spell.replaced_words))  # 0

input_term_2 = (
    "whereis th elove hehad dated forImuch of thepast who "
    "couqdn'tread in sixtgrade and ins pired him"
)
# max edit distance per lookup (per single word, not per whole input string)
suggestions = sym_spell.lookup_compound(input_term_2, max_edit_distance=2)
# display suggestion term, edit distance, and term frequency
for suggestion in suggestions:
    print(suggestion)

print(len(sym_spell.replaced_words))  # 9
```

**Comment by ByUnal** [comment]
I really appreciated for this detailed answer. Actually, I can use these checker methods for both entire sentence and words. So, both methodology you shared are valuable for me. I'm going to try both of these methods, I'll let you know anything wrong comes up. Thanks again :)
